### ISSUE TITLE
-n and -r don't compose?

### ISSUE THREAD

**Issue by borkdude** [cognitect-labs/test-runner#17]
If you use the -n option together with the -r option, it seems only the -n option is used.

**Comment by vemv** [comment]
Hi,

I think now they compose too much :)

If I pass ` clojure -M:test -n foo-test` it's a reasonable expectation that only _that_ test will be executed. However all other existing tests will also be executed.

There's the specific precedent of `lein test :only foo`, which will run only `foo` and nothing else, no matter what. 

I'm failing to find an "only" semantic in `-main`.

Sounds good to reopen? Can also report in isolation.

---

Current workaround: `-n foo -r "aaaaaaaaaaa"` where `aaaaaaaaaaa` will intentionally match nothing.

**Comment by vemv** [comment]
I didn't notice https://github.com/cognitect-labs/test-runner/issues/29 and the subsequent commit.

Bumping `com.cognitect/test-runner` fixed this for me.

Sorry for the noise!
