### ISSUE TITLE
ClojureScript support

### ISSUE THREAD

**Issue by swannodette** [cognitect-labs/test-runner#2]
Thoughts / opinions about ClojureScript support? It would be nice if this tool could cover the two common use cases.

**Comment by levand** [comment]
No objections in principle, but we'd need to make some decisions. 

As far as I know there is no single widely accepted way to build ClojureScript using deps.edn yet; some people write their own compile scripts, some people use Figwheel, etc.

Adding CLJS support would involve either making decisions about how to compile, or defining integration points to point the test runner at existing compiled JS. 

Another thing that would need to be decided is what kind of execution environment to use. Node would seem to be the default, but I have seen projects which use a headless browser for their CLJS test runner so they can test DOM/React stuff.

**Comment by swannodette** [comment]
@levand CLJS support should just emulate what you've done for Clojure. I think the only additional flags that would be relevant for ClojureScript would be one to set the compilation level `-O` and another `-js` to set arbitrary runner command. I've already done a version of what would be required here for `cljs.main` and can likely just reuse most of that to make this work.

**Comment by samumbach** [comment]
👍 I'd love the ability to run cljs tests for a single namespace or var.

Any concerns about incremental builds or compilation flag changes? I've run into a lot of trouble when switching between different optimization levels or changing other cljs compiler options without performing a `clean`. My best practice for the moment is using completely separate output paths for different cljs compiler flags.

**Comment by Olical** [comment]
I just released [cljs-test-runner](https://github.com/Olical/cljs-test-runner). Completely separate code, but you might be able to take things from it, which you're more than welcome to do. Or maybe these two tools will complement each other well enough anyway.

I haven't got var / ns filtering in mine yet, but it wouldn't be too hard to add.

**Comment by Olical** [comment]
FYI, I have a PR open for my aforementioned cljs-test-runner (https://github.com/Olical/cljs-test-runner/pull/5) that matches the functionality of this project. So you can now run a single namespace or var as well as filter by meta keywords, @sumbach. If anyone wants to rip that code out and put it in here some day, be my guest. Maybe it's best to keep them separate though.

If anyone wants to try out that PR and let me know how they get on that'd be amazing. If not I'll have it released under version `2.0.0` soon enough.

**Comment by puredanger** [comment]
It's been a couple years. :)  Current thoughts on this? I'm happy for them to remain independent as these might need to rev independently, I don't track cljs closely enough to know.

**Comment by Olical** [comment]
I'm not really doing much cljs these days (lots of clj though!) and cljs-test-runner is still working fine for the most part AFAIK (❤️ Clojure ecosystem stability) but it is a pretty involved project doing some _Fun_ and _Opinionated_ things to work.

If you ever wanted to add CLJS support here I wouldn't necessarily base it on my work, there may be _much_ better ways out there.

**Comment by puredanger** [comment]
Ok, I'm going to close this for now and leave this lib as clj only. Will revisit in the future.
