### ISSUE TITLE
Release on Maven?

### ISSUE THREAD

**Issue by vemv** [cognitect-labs/test-runner#25]
Hi,

I appreciate `test-runner`'s lean-ness and simplicity which can lead to solutions that can be well understood and maintained.

This IMO contrasts with`lein test`. Its `test.clj` backing namespace is not a vanilla one that can be `require`d and executed by vanilla (non-lein-plugin) Clojure code.

However that's just _one_ of the many concerns that may lead a team or individual to choose tools.deps over Lein, or vice versa.

Accordingly, I'd like to suggest that this library is also offered as a Maven artifact, so that one can choose to use it from a Lein project.

There are alternatives (forking, vendoring, using `lein-git-down`, etc) but one can also consider the technical and social risk/cost of deviating from an official artifact.

WDYT?

Thanks - V

**Comment by puredanger** [comment]
Not planning to release as an artifact, will be implementing a release tagging strategy
