### ISSUE TITLE
Don't system/exit in -X runner

### ISSUE THREAD

**Issue by puredanger** [cognitect-labs/test-runner#34]
-X is on the path to take care of this so when that is in a stable release, stop doing that here.

**Comment by vazub** [comment]
Sorry to necro this issue/commit, but it appears that this change makes it show an exception and a stack trace when running with Babashka. Reverting it to previous logic helps to make it pretty again. And `clj -X:test` works fine with previous logic as well.

**Comment by puredanger** [comment]
There are a bunch of things to consider here. The most important aspect is to get a non-zero exit code from the test process when the tests fail.

One way to do that is via System/exit, but that is hostile to testing and we're not going back to that. Another is to signal an error by throwing, which runners like clj (the primary target here) interpret as an error condition and convey as an error exit code. The clj runner also interprets ex-info as an error to catch and print to the user.

In the future, there may be some way to convey a preferred exit code to clj via some other mechanism, but that does not currently exist.

If you're not seeing what you want with babashka, that seems like an issue to convey to babashka.

**Comment by vazub** [comment]
Is there a specific reason why you treat test failure the same as test error? In my limited understanding, test failures are rather expected outcomes, that would not deserve an exception throw. Why not throw for errors only and leave failures be?
```
    (when (> error 0)
      (throw (ex-info "Test errors occurred." {})))))
```

**Comment by puredanger** [comment]
This is commonly used by CI that does a test run and uses the exit code as a signal that tests failed. From that perspective, either a test failure or a test error should be seen as "failing test run".
