### ISSUE TITLE
Tests are run in `user` namespace

### ISSUE THREAD

**Issue by raystubbs** [cognitect-labs/test-runner#38]
Using `clj -X:test` seems to run the tests in the `user` namespace, which breaks tests that rely on `*ns*`.  Here's a repro.

```clj
(ns example.core-test
  (:require
    [clojure.test :refer [deftest is]]))

(deftest example-test
  (is (= (str *ns*) "example.core-test")))
```

Result:
```
FAIL in (example-test) (core_test.cljc:24)
expected: (= (str *ns*) "example.core-test")
  actual: (not (= "user" "example.core-test"))
```

**Comment by puredanger** [comment]
Do you have an example closer to what actually fails due to this?

**Comment by raystubbs** [comment]
Yeah, [this test](https://github.com/raystubbs/FkCSS/blob/master/test/fkcss/core_test.cljc#L10-L13) fails since the `defclass` macro bases class names on the current ns.

**Comment by puredanger** [comment]
I don't think there is any good reason to have this expectation. clojure.test tests can be run from any namespace and often are run from namespaces other than the place where they are defined.

If you want to enforce this constraint, you can do so via a :once fixture:

```clojure
(defn ns-fixture
  [f]
  (in-ns 'example.core-test)
  (f))

(use-fixtures :once ns-fixture)
```

**Comment by raystubbs** [comment]
Hmm, okay.  Seems odd that you can't depend on the namespace; but makes some sense if that's the convention.
