### ISSUE TITLE
test-runner does not exit correctly since v0.5.0

### ISSUE THREAD

**Issue by gnarroway** [cognitect-labs/test-runner#41]
## Background
- I am migrating https://github.com/gnarroway/hato to use GitHub actions for the test/publish CI workflow (previously circleCI)
- As part of this, I am using deps.edn with this test-runner library
- cli version 1.11.1.1155, java 11 or 17

## Behaviour
- Using v0.5.0 or later, the test job hangs (invoking `clojure -X:test` with  `:exec-fn     cognitect.test-runner.api/test`), *after* logging the test results (0 failures, 0 errors.)
- Downgrading to v0.4.0, the test job finishes successfully

## Analysis
- 0.5.0 included a change to the exit logic, so am guessing it is somehow related to this and the job is not exiting correctly (or in a manner GitHub actions expects, though I don't know what that is)

**Comment by puredanger** [comment]
Does it really "hang", or is it waiting for `future` threads to exit?

I am successfully using clj with test-runner in github actions myself and not seeing any issues btw.

**Comment by gnarroway** [comment]
Thanks for the quick response. Given your hint, I will have a deeper look on my end and see how I go.
