### ISSUE TITLE
Unable to run tests based on specific directory

### ISSUE THREAD

**Issue by nvseenu** [cognitect-labs/test-runner#42]
Hi All,

   My application has below directory structure.

       src 
       |
       - ---hi.clj
       test
       |    
       ----- unit
       |       |
       |       ------ hi_test.clj 
       |
       ------- integration
                |
                ----  hi_test.clj

I was trying to run tests based on directory as per the test-runner document.  I was getting the below error:

>  clj -X:test :dirs ["test/integration"]
> Execution error (IllegalArgumentException) at cognitect.test-runner/test (test_runner.clj:68).
> No implementation of method: :as-file of protocol: #'clojure.java.io/Coercions found for class: clojure.lang.Symbol

Later, I gave the args like below and it started working. ( I just surrounded ["test/integration" with single quotes.)

>  clj -X:test :dirs '["test/integration"]'

Am using ubuntu 20.   It took 4 hours to figure out the mistake.  Can it be included in the document / example? so that no one will have to waste the time like me.

**Comment by puredanger** [comment]
Yes, I can point to the quoting docs for clj at https://clojure.org/reference/deps_and_cli#quoting

thanks...

**Comment by nvseenu** [comment]
Thanks a lot for quick response.  It is my bad, i missed  CLI doc. 

I think there is a typo error in the commit 
clj -X:test :dirs '["test" "interation"]'

**Comment by puredanger** [comment]
thx :)
