### ISSUE TITLE
Tests do not finish if an agent has been started.

### ISSUE THREAD

**Issue by farbeiza** [cognitect-labs/test-runner#43]
If an agent is started, tests do not finish, waiting for the agent threads to finish:

These files should reproduce the issue:
_deps.edn_:
```
{:paths ["src"]
 :deps {}
 :aliases {:test {:extra-paths ["test"]
                  :extra-deps {io.github.cognitect-labs/test-runner {:git/sha "a522ab2851a2aa5bf9c22a942b45287a3a019310"}}
                  :main-opts ["-m" "cognitect.test-runner"]
                  :exec-fn cognitect.test-runner.api/test}}}
```

_core_test.clj_:
```
(ns core-test
  (:require [clojure.test :refer :all]))

(deftest duration-test
  (let [a (agent 0)]
    (send a inc)
    (await a)
    (is (= 1 @a))))
```

I've seen a PR which could be very useful for this: [Add before and after options](https://github.com/cognitect-labs/test-runner/pull/21)
since it will allow to run `(shutdown-agents)` after running the tests.

**Comment by puredanger** [comment]
We used to have such logic (see https://github.com/cognitect-labs/test-runner/commit/23771f4bee77d4e938b9bfa89031d2822b4e2622) but that was removed in favor of having the execution context handle it.

How are you running test-runner?

**Comment by puredanger** [comment]
And if you are running with the Clojure CLI, which version (exit behavior has changed there several times)?

**Comment by farbeiza** [comment]
I'm running it with clj -X

```
$ clj -X:test

Running tests in #{"test"}

Testing core-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.
```

Version is:
```
$ clj -version
Clojure CLI version 1.11.1.1165
```

**Comment by seancorfield** [comment]
I think it's okay for `-M` contexts to call `shutdown-agents` at the end but it is **not** okay for `-X` contexts to do this since it undermines programmatic invocation of the test runner.

**Comment by raystubbs** [comment]
Seems like this happens if a `Timer`, or any other user thread remains alive too... seems like it'd be good to have something (on an opt-in basis) that just calls `System/exit` after all the test runner stuff finishes.

**Comment by puredanger** [comment]
I can't repro this with current version of the Clojure CLI, which installs an agent thread pool that makes agent threads into daemon threads.
